version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6

  web:
    image: habits:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # Celery beat scheduler
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  pgdata: