version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env
    command: gunicorn habits_project.config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env
    command: celery -A habits_project.config.celery worker --loglevel=info
    depends_on:
      - redis
      - db

  beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env
    command: celery -A habits_project.config.celery beat --loglevel=info
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles

volumes:
  pgdata:
  static_volume:
