version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis for Celery broker and cache
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Backend application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head &&
             gunicorn app.main:app
               --workers=4
               --bind=0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # Celery beat scheduler
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  pgdata: