# Generated by Django 4.2.23 on 2025-06-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_reward", models.BooleanField(default=False)),
                ("reward_text", models.CharField(blank=True, max_length=255)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("duration_seconds", models.PositiveIntegerField(default=60)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_reward": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_for",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
