name: CI & CD

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --no-dev

      - name: Run tests
        run: poetry run pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4

      - name: Copy deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan your.domain.com >> ~/.ssh/known_hosts

      - name: Pull & restart on server
        run: |
          ssh youruser@your.domain.com << 'EOF'
            cd /srv/app
            git fetch origin develop
            git reset --hard origin/develop
            source .venv/bin/activate
            poetry install --no-dev
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart app.service
          EOF